cerveza_homepage:
    path:     /{id}
    defaults: { _controller: CervezaBundle:Default:index, id:1 }

cerveza_homepage:
    path:     /{nombre}/{pais}
    defaults: { _controller: CervezaBundle:Default:insertarCerveza }
