cerveza_homepage:
    path:     /{id}
    defaults: { _controller: CervezaBundle:Default:index, id:1 }

insertarCerveza:
    path:     /insertarCerveza/{nombre}/{pais}
    defaults: { _controller: CervezaBundle:Default:insertarCerveza, nombre:'er',  pais:'rhefui' }
